# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: gecko_taskgraph.loader.transform:loader

transforms:
    - gecko_taskgraph.transforms.release_deps:transforms
    - gecko_taskgraph.transforms.bouncer_aliases:transforms
    - gecko_taskgraph.transforms.task:transforms

kind-dependencies:
    - release-bouncer-check

job-defaults:
    description: Update bouncer aliases job
    worker-type: bouncer
    worker:
        implementation: bouncer-aliases
    scopes:
        by-release-level:
            production:
                - project:comm:thunderbird:releng:bouncer:action:aliases
                - project:comm:thunderbird:releng:bouncer:server:production
            staging:
                - project:comm:thunderbird:releng:bouncer:action:aliases
                - project:comm:thunderbird:releng:bouncer:server:staging
    run-on-projects: []
    shipping-phase: ship
    treeherder:
        symbol: Rel(BncAlias)
        kind: test
        tier: 1

jobs:
    thunderbird:
        bouncer-products-per-alias:
            by-release-type:
                beta:
                    thunderbird-beta-latest-ssl: installer-ssl
                    thunderbird-beta-latest: installer
                    thunderbird-beta-msi-latest-ssl: msi
                    thunderbird-beta-msix-latest-ssl: msix
                release:
                    # Disable on comm-esr115 when the next esr is released
                    thunderbird-latest-ssl: installer-ssl
                    thunderbird-latest: installer
                    thunderbird-msi-latest-ssl: msi
                    thunderbird-msix-latest-ssl: msix
                default: {}
        shipping-product: thunderbird
        treeherder:
            platform: thunderbird-release/opt
