# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
s3_bucket_paths:
    by-platform:
        shippable-l10n-pre:
            - pub/thunderbird/candidates
default_locales:  # if given an empty locale, use these locales
    - en-US
tasktype_map:  # Map task reference to task type.
    shippable-l10n-pre-signing: signing

# A default entry, which the mappings below extend and override.
# Final 'destinations' will be the product of:
# s3_bucket_paths + destinations + locale_prefix + pretty_name
default: &default
    from:
        - shippable-l10n-pre-signing
    all_locales: false
    description: "TO_BE_OVERRIDDEN"
    locale_prefix: ''
    source_path_modifier: ''
    destinations:  # locale_prefix is appended
        - ${version}-candidates/build${build_number}/source

# Configuration for individual files. Extends 'default', above.
mapping:
    strings_all.tar.zst:
        <<: *default
        description: "Strings sources for localuized builds and langpacks"
        pretty_name:
            by-platform:
                shippable-l10n-pre: thunderbird-${version}.strings_all.tar.zst
        checksums_path:
            by-platform:
                shippable-l10n-pre: source/thunderbird-${version}.strings_all.tar.zst
    strings_all.tar.zst.asc:
        <<: *default
        description: "Detached signature for the strings source file"
        pretty_name:
            by-platform:
                shippable-l10n-pre: thunderbird-${version}.strings_all.tar.zst.asc
        checksums_path:
            by-platform:
                shippable-l10n-pre: source/thunderbird-${version}.strings_all.tar.zst.asc
    l10n-changesets.json:
        <<: *default
        description: "Source info used to build strings_all.tar.zst"
        pretty_name:
            by-platform:
                shippable-l10n-pre: thunderbird-${version}.l10n-changesets.json
        checksums_path:
            by-platform:
                shippable-l10n-pre: source/thunderbird-${version}.l10n-changesets.json
    l10n-changesets.json.asc:
        <<: *default
        description: "Detached signature for changesets file"
        pretty_name:
            by-platform:
                shippable-l10n-pre: thunderbird-${version}.l10n-changesets.json.asc
        checksums_path:
            by-platform:
                shippable-l10n-pre: source/thunderbird-${version}.l10n-changesets.json.asc
